packages:
  - "packages/*"
  - "apps/*"
catalog:
  '@types/node': 22.20.1
  '@modelcontextprotocol/sdk': ^1.29.0
  dotenv: 17.2.3
  typescript: 5.9.3
  vitest: ^4.1.4
  zod: ^4.3.6
allowBuilds:
  '@nestjs/core': false
  '@prisma/engines': true
  esbuild: true
  msw: false
  prisma: false
  sharp: true
  unrs-resolver: true
