export {
    extractUserMemoryCandidates,
    USER_MEMORY_EXTRACTION_MODEL_ID,
    USER_MEMORY_EXTRACTION_PROMPT,
    userMemoryExtractorOutputSchema,
} from './candidate-extractor'
export { buildUserMemoryContextMessages } from './context-builder'
export {
    buildUserMemoryExtractionJobInput,
    createUserMemoryExtractionPipeline,
    processCompletedTurnForMemory,
    type ProcessCompletedTurnForMemoryInput,
} from './extraction-pipeline'
export { closeUserMemoryPostgresStore, createPostgresUserMemoryStore, getUserMemoryStore, resetUserMemoryStoreForTests } from './provider'
export { normalizeUserMemorySemanticQuery, retrieveRelevantUserMemories } from './retrieval'
export {
    getUserMemoryRuntimeConfig,
    type UserMemoryRuntimeConfig,
    type UserMemorySemanticProviderKind,
    type UserMemoryStoreMode,
    USER_MEMORY_EMBEDDING_DIMENSIONS_ENV,
    USER_MEMORY_EMBEDDING_MODEL_ID,
    USER_MEMORY_MAX_SELECTED_MEMORIES,
    USER_MEMORY_MAX_TEXT_CHARS,
    USER_MEMORY_MAX_TOTAL_CHARS,
    USER_MEMORY_MIN_CONFIDENCE,
    USER_MEMORY_POSTGRES_SCHEMA,
    USER_MEMORY_SCHEMA_VERSION,
    USER_MEMORY_SEMANTIC_INDEX_FIELDS,
    USER_MEMORY_SEMANTIC_INDEX_VERSION,
    USER_MEMORY_SEMANTIC_PROVIDER_KIND_REAL,
    USER_MEMORY_SEMANTIC_QUERY_HEAD_CHARS,
    USER_MEMORY_SEMANTIC_QUERY_MAX_CHARS,
    USER_MEMORY_SEMANTIC_QUERY_TAIL_CHARS,
    USER_MEMORY_SEMANTIC_SCORE_THRESHOLD,
    USER_MEMORY_SEMANTIC_TIMEOUT_MS,
    USER_MEMORY_SEMANTIC_TOP_K,
} from './runtime-config'
export {
    type SelectedUserMemory,
    type UserMemoryAction,
    type UserMemoryCandidate,
    type UserMemoryDocument,
    type UserMemoryExtractionJob,
    type UserMemoryExtractionResult,
    type UserMemoryIdentity,
    type UserMemoryIdentityPolarity,
    type UserMemoryPath,
    type UserMemoryPromotionResult,
    type UserMemoryRejectionReason,
    type UserMemorySemanticCandidate,
    type UserMemorySemanticIndexField,
    type UserMemorySemanticMetadata,
    type UserMemorySemanticProviderKind as UserMemorySemanticProviderKindFromSchema,
    type UserMemorySemanticRetrievalRequest,
    type UserMemorySemanticSearchItem,
    type UserMemorySafeShortTermContext,
    type UserMemorySource,
    type UserMemorySourceSignal,
    type UserMemoryStability,
    type UserMemoryStatus,
    type UserMemoryType,
    type UserMemoryWriteResult,
    normalizeUserMemoryDocument,
    selectedUserMemorySchema,
    userMemoryActionSchema,
    userMemoryCandidateSchema,
    userMemoryDocumentSchema,
    userMemoryExtractionJobSchema,
    userMemoryIdentityPolaritySchema,
    userMemoryIdentitySchema,
    userMemoryPathSchema,
    userMemorySemanticCandidateSchema,
    userMemorySemanticIndexFieldSchema,
    userMemorySemanticMetadataSchema,
    userMemorySemanticProviderKindSchema,
    userMemorySemanticRetrievalRequestSchema,
    userMemorySemanticSearchItemSchema,
    userMemorySafeShortTermContextSchema,
    userMemorySourceSchema,
    userMemorySourceSignalSchema,
    userMemoryStabilitySchema,
    userMemoryStatusSchema,
    userMemoryTypeSchema,
    USER_MEMORY_NAMESPACE_PREFIX,
    USER_MEMORY_TAG_LIMIT,
    USER_MEMORY_TAG_MAX_LENGTH,
} from './state-schema'
export { createUserMemoryService, getUserMemoryService, userMemoryService, type UserMemoryService } from './user-memory-service'
export {
    buildUserMemoryNamespace,
    buildUserMemorySemanticMetadata,
    buildUserMemoryStableKey,
    clipUserMemoryText,
    createUserMemoryDocument,
    isUserMemorySemanticEligible,
    normalizeUserMemoryStableKey,
    normalizeUserMemoryTag,
    normalizeUserMemoryTags,
    readUserMemoryDocumentValue,
    sanitizeUserMemoryReason,
    type UserMemoryCandidateValidationResult,
    type ValidatedUserMemoryCandidate,
    validateUserMemoryCandidate,
} from './validation'
