export { localFileSummaryPromptAdapter } from './local-file-summary-prompt-adapter'
export { projectDocsResourceAdapter } from './project-docs-resource-adapter'
export { getRemoteMcpToolDefinition, getRemoteMcpToolDefinitions } from './remote-mcp-tool-adapter'
export { weatherToolAdapter } from './weather-tool-adapter'
export type { MCPPromptAdapter, MCPResourceAdapter, MCPToolAdapter } from './types'
