import type { AiMindModelCatalogItem } from '../types'

export const modelCatalog = [
    {
        availableIn: ['development'],
        capabilities: {
            chat: true,
            embedding: false,
            jsonOutput: true,
            streaming: true,
            tasklist: true,
            toolCalling: true,
        },
        enabled: true,
        id: 'ollama/qwen3-4b',
        label: 'qwen3-4b',
        modelKey: 'qwen3-4b',
        provider: 'ollama',
        providerModel: 'qwen3:4b',
    },
    {
        availableIn: ['development'],
        capabilities: {
            chat: true,
            embedding: false,
            jsonOutput: true,
            streaming: true,
            tasklist: true,
            toolCalling: true,
        },
        enabled: true,
        id: 'ollama/qwen3-8b',
        label: 'qwen3-8b',
        modelKey: 'qwen3-8b',
        provider: 'ollama',
        providerModel: 'qwen3:8b',
    },
    {
        availableIn: ['development'],
        capabilities: {
            chat: true,
            embedding: false,
            jsonOutput: true,
            streaming: true,
            tasklist: true,
            toolCalling: true,
        },
        enabled: true,
        id: 'ollama/qwen3-14b',
        label: 'qwen3-14b',
        modelKey: 'qwen3-14b',
        provider: 'ollama',
        providerModel: 'qwen3:14b',
    },
    // {
    //     availableIn: ['development', 'production'],
    //     capabilities: {
    //         chat: true,
    //         embedding: false,
    //         jsonOutput: true,
    //         streaming: true,
    //         tasklist: true,
    //         toolCalling: true,
    //     },
    //     enabled: true,
    //     id: 'deepseek/deepseek-v4-flash',
    //     label: 'deepseek-v4-flash',
    //     modelKey: 'deepseek-v4-flash',
    //     provider: 'deepseek',
    //     providerModel: 'deepseek-v4-flash',
    // },
    // {
    //     availableIn: ['development', 'production'],
    //     capabilities: {
    //         chat: true,
    //         embedding: false,
    //         jsonOutput: true,
    //         streaming: true,
    //         tasklist: true,
    //         toolCalling: true,
    //     },
    //     enabled: true,
    //     id: 'deepseek/deepseek-v4-pro',
    //     label: 'deepseek-v4-pro',
    //     modelKey: 'deepseek-v4-pro',
    //     provider: 'deepseek',
    //     providerModel: 'deepseek-v4-pro',
    // },
    {
        availableIn: ['development', 'production'],
        capabilities: {
            chat: true,
            embedding: false,
            jsonOutput: true,
            streaming: true,
            tasklist: true,
            toolCalling: true,
        },
        enabled: true,
        id: 'deepseek/deepseek-v4-flash',
        label: 'deepseek-v4-flash',
        modelKey: 'deepseek-v4-flash',
        provider: 'doubao',
        providerModel: 'deepseek-v4-flash',
    },
    {
        availableIn: ['development', 'production'],
        capabilities: {
            chat: true,
            embedding: false,
            jsonOutput: true,
            streaming: true,
            tasklist: true,
            toolCalling: true,
        },
        enabled: true,
        id: 'deepseek/deepseek-v4-pro',
        label: 'deepseek-v4-pro',
        modelKey: 'deepseek-v4-pro',
        provider: 'qwen',
        providerModel: 'deepseek-v4-pro',
    },
    {
        availableIn: ['development', 'production'],
        capabilities: {
            chat: true,
            embedding: false,
            jsonOutput: true,
            streaming: true,
            tasklist: true,
            toolCalling: true,
        },
        enabled: true,
        id: 'qwen/qwen3.6-flash',
        label: 'qwen3.6-flash',
        modelKey: 'qwen3.6-flash',
        provider: 'qwen',
        providerModel: 'qwen3.6-flash',
    },
    // {
    //     availableIn: ['development', 'production'],
    //     capabilities: {
    //         chat: true,
    //         embedding: false,
    //         jsonOutput: true,
    //         streaming: true,
    //         tasklist: true,
    //         toolCalling: true,
    //     },
    //     enabled: true,
    //     id: 'qwen/qwen3.6-plus',
    //     label: 'qwen3.6-plus',
    //     modelKey: 'qwen3.6-plus',
    //     provider: 'qwen',
    //     providerModel: 'qwen3.6-plus',
    // },
    {
        availableIn: ['development', 'production'],
        capabilities: {
            chat: true,
            embedding: false,
            jsonOutput: true,
            streaming: true,
            tasklist: true,
            toolCalling: true,
        },
        enabled: true,
        id: 'qwen/qwen3.7-plus',
        label: 'qwen3.7-plus',
        modelKey: 'qwen3.7-plus',
        provider: 'qwen',
        providerModel: 'qwen3.7-plus',
    },
    //火山引擎
    {
        availableIn: ['development', 'production'],
        capabilities: {
            chat: true,
            embedding: false,
            jsonOutput: true,
            streaming: true,
            tasklist: true,
            toolCalling: true,
        },
        enabled: true,
        id: 'doubao/Doubao-Seed-2.0-Code',
        label: 'Doubao-Seed-2.0-Code',
        modelKey: 'Doubao-Seed-2.0-Code',
        provider: 'doubao',
        providerModel: 'Doubao-Seed-2.0-Code',
    },
    {
        availableIn: ['development', 'production'],
        capabilities: {
            chat: true,
            embedding: false,
            jsonOutput: true,
            streaming: true,
            tasklist: true,
            toolCalling: true,
        },
        enabled: true,
        id: 'doubao/doubao-seed-2.0-pro',
        label: 'doubao-seed-2.0-pro',
        modelKey: 'doubao-seed-2.0-pro',
        provider: 'doubao',
        providerModel: 'doubao-seed-2.0-pro',
    },
    {
        availableIn: ['development', 'production'],
        capabilities: {
            chat: true,
            embedding: false,
            jsonOutput: true,
            streaming: true,
            tasklist: true,
            toolCalling: true,
        },
        enabled: true,
        id: 'doubao/doubao-seed-2.0-mini',
        label: 'doubao-seed-2.0-mini',
        modelKey: 'doubao-seed-2.0-mini',
        provider: 'doubao',
        providerModel: 'doubao-seed-2.0-mini',
    },
    {
        availableIn: ['development', 'production'],
        capabilities: {
            chat: true,
            embedding: false,
            jsonOutput: true,
            streaming: true,
            tasklist: true,
            toolCalling: true,
        },
        enabled: true,
        id: 'doubao/Kimi-K2.6',
        label: 'Kimi-K2.6',
        modelKey: 'Kimi-K2.6',
        provider: 'doubao',
        providerModel: 'Kimi-K2.6',
    },
] satisfies AiMindModelCatalogItem[]
